// ------------------------------
// Ledger event structure
// ------------------------------
export interface LedgerEvent {
  id?: string; // optional, generated by server
  batchId: string;
  stage: 'farmer' | 'lab' | 'manufacturer';
  timestamp?: string; // optional, server can set
  addedBy: string;
  data: Record<string, any>;
}

// ------------------------------
// Farmer portal
// ------------------------------
export type QuantityUnit = 'Kg' | 'Ton';

export type ProductName =
  | 'Neem' | 'Tulsi' | 'Aloe Vera' | 'Ashwagandha' | 'Amla'
  | 'Brahmi' | 'Shatavari' | 'Giloy' | 'Haritaki' | 'Baheda'
  | 'Triphala' | 'Turmeric' | 'Ginger' | 'Licorice' | 'Gokshura'
  | 'Coconut';

export interface FarmerRecord {
  batchId: string;
  farmerId: string;
  productName: string;
  quantityValue: number;
  quantityUnit: 'Kg' | 'Ton';
  harvestedDateISO: string;
  state: string;
  district: string;
  villageTown: string;
  latitude: number;
  longitude: number;
  addedBy: string;
  createdAtISO: string;
}


// ------------------------------
// Lab portal
// ------------------------------
export interface LabResult {
  batchId: string;
  labId: string;
  testedBy: string;
  testedAtISO: string;
  moisture: number;
  pesticide: number;
  quality: string; // accept grade letters or Pass/Fail
  labStaff?: string;
}

export interface LabBatch {
  id: string;
  productName: string;
  farmerName: string;
  collectionDate: string;
  status: 'PENDING' | 'TESTED' | 'REJECTED';
  addedBy?: string;
}

// ------------------------------
// Manufacturer portal
// ------------------------------
export interface RawBatch {
  id: string;
  productName: string;
  farmer: {
    name: string;
    farmerId: string;
    location: string;
  };
  labTest?: LabResult;
  collectionDate?: string;
  status?: string;
}

export interface ManufacturedBatch {
  manufacturedBatchId: string;
  companyName: string;
  productName: string;
  productType: 'Powder' | 'Capsule' | 'Paste' | 'Oil' | 'Syrup' | 'Shampoo';
  ingredients: string;
  addedBy: string;
  manufacturedAt: string;
  rawBatches: RawBatch[];
}

// ------------------------------
// Optional session interface
// ------------------------------
export interface AppSession {
  companyName: string;
  catalog?: Record<string, Record<string, string[]>>; // productType -> productName -> ingredients
}
